Repository PI2-viticultura/SmartVit-Administrator, pull requests merged in 2020-10, with the labels that each got.

#2 Cadastrar Contrato
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/components/Navbar.js
  src/components/SidebarData.js
  src/components/style.css
  src/index.css
  src/index.js
  src/scenes/contract/index.js
  src/scenes/contract/style.css
  src/scenes/register-contract/index.js
  src/scenes/register-contract/style.css
  src/services/api.js
  src/theme.js
  src/utils/masks.js
Labels: enhancement

#4 US1 - Cadastrar/Editar Vinícola
  src/App.js
  src/components/SidebarData.js
  src/globals/globalStyle.css
  src/scenes/register-contract/index.js
  src/scenes/winery/index.js
Labels: hacktoberfest-accepted

#3 Feature/19 us26 visualizar solicitações
  package-lock.json
  package.json
  src/App.js
  src/components/SidebarData.js
  src/components/style.css
  src/scenes/orders/index.js
  src/scenes/orders/style.css
Labels: hacktoberfest-accepted

#6 US04 - Listar vinícolas cadastradas
  package-lock.json
  src/App.js
  src/components/Navbar.js
  src/components/SidebarData.js
  src/globals/globalStyle.css
  src/scenes/list-winery/index.js
  src/scenes/list-winery/style.css
  src/scenes/register-contract/style.css
Labels: enhancement, hacktoberfest-accepted

#8 Configuração Deploy Continuo
  .env
  src/scenes/list-winery/index.js
  src/scenes/orders/index.js
  src/scenes/register-contract/index.js
  src/scenes/user-edit/index.js
  src/scenes/user-list/index.js
  src/scenes/user-register/index.js
  src/scenes/winery/index.js
  src/services/api-admin.js
  src/services/api-user.js
  src/services/api-winery.js
  src/services/api.js
Labels: enhancement, hacktoberfest-accepted
